### ISSUE TITLE
2020-10-23 meeting comments

### ISSUE THREAD

**Issue by MatthewSteen** [MatthewSteen/MS-AREN-6960-Masters-Report#16]
2020-10-23 meeting comments from @krarti.

General Comments
- [x] add more detail to measures

Specific Comments
- [x] add table of measure codes vs description
- [x] add table showing comparison/verification that comfort is not compromised by measures (unmet hours)
- [x] use $/m2 rather than total
- [x] A1 (#4) try replacing insulation layer with PCM on exterior wall and/or ceiling
- [x] M1 (#8) run in humid climate to test that savings are greater than Denver
- [x] M2 (#9) change schedule to align with utility for savings impact
- [x] P1 (#10) change operation scheme to test savings impact, when is CHP used?
